// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rLL3fgiaZbtbK8lqA8vQlY5WrTLnYWw',
    appId: '1:723560354101:web:4b9ab109f67ab192b8fc7c',
    messagingSenderId: '723560354101',
    projectId: 'task-manager-aed7d',
    authDomain: 'task-manager-aed7d.firebaseapp.com',
    storageBucket: 'task-manager-aed7d.firebasestorage.app',
    measurementId: 'G-07CCFKQ17E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_HIZ7exY_ZEH565rYXjp0pqPRpE6l9qg',
    appId: '1:723560354101:android:92f89edf23f08631b8fc7c',
    messagingSenderId: '723560354101',
    projectId: 'task-manager-aed7d',
    storageBucket: 'task-manager-aed7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6POkYI6mFZy_VovhovsVnfaf09hisWxw',
    appId: '1:723560354101:ios:a0bcc6969b4ddf66b8fc7c',
    messagingSenderId: '723560354101',
    projectId: 'task-manager-aed7d',
    storageBucket: 'task-manager-aed7d.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerBloc',
  );
}
